Clear interceptors on configure #2
micky2be/superlogin-client pull request #20
Opened 2016-09-01 08:37 UTC by peteruithoven

Currently when configure is called multiple times there will be multiple request interceptors, which usually means the checkRefresh is called multiple times uncecesarily. This also solves: #17

2016-09-01 10:53 UTC, micky2be commented on src/index.js
> -		this._http = axios.create();
Could you set `this._http` to `null` in the constructor please.

2016-09-01 11:13 UTC, peteruithoven commented on src/index.js
> -		this._http = axios.create();
Sure, done.

2016-09-06 11:32 UTC, peteruithoven commented
@micky2be what do you think of it like this? Is this okay?

2016-09-08 03:29 UTC, micky2be commented
The fact that we have `getHttp` bother me, I don't wanna introduce a different bug.
I still believe that removing the event and putting them back would be better.

If you are not up for the task, give me some time so I can do it myself.

2016-09-12 07:08 UTC, peteruithoven commented
Which event are you talking about?

2016-09-12 08:39 UTC, micky2be commented
The interceptors.
They need to be cleaned with the API and re-attached during the setup.
This will guaranty everything to work as intended.

2016-09-12 10:03 UTC, peteruithoven commented
I'm not following at all...
Cleaned with what API? 
During which setup? Do you mean the configure() method of superlogin-client? 
Why clean something and then re-attach something? Are you talking about interseptors the user might ave added after using the getHttp method? 

Maybe we can, instead of creating a new axios instance, remove only the interseptors we've added?

2016-09-13 02:03 UTC, micky2be commented
Instead of re-instanciate Axios we could remove the interceptors and reattached it.
It will avoid people calling getHttp to use an old version.

2016-09-13 05:44 UTC, peteruithoven commented
True, like I was doing with the following pull request?
https://github.com/micky2be/superlogin-client/pull/18/commits/0c3cc0cfcdba0733589b5fcbed9426d9e0c05a7e

2016-09-13 09:19 UTC, micky2be commented
Yes

2016-09-13 11:02 UTC, peteruithoven commented
I'll revert back to that solution then. I'll also open an issue at axios about a clear function.

2016-09-13 12:02 UTC, micky2be commented
I gave you tbe api to use last time. Why don't you use it?

’interceptors.request.eject‘

2016-09-13 13:29 UTC, peteruithoven commented
I explained why here: https://github.com/micky2be/superlogin-client/pull/18/commits/0c3cc0cfcdba0733589b5fcbed9426d9e0c05a7e#r76944725

2016-09-15 06:37 UTC, micky2be requested changes
Please use the Axios API to remove the handlers

2016-09-15 09:37 UTC, peteruithoven commented
I'm now storing the specific id's so we can eject them. This is probably what you meant? 
This has as added benefit that the user's added interceptors remain untouched.

2016-09-20 01:37 UTC, micky2be commented
yes, this looks better.
Thank you

2016-09-20 01:37 UTC, micky2be approved these changes

2016-09-20 01:37 UTC, merged