Handle no response
micky2be/superlogin-client pull request #56
Opened 2017-04-10 15:57 UTC by peteruithoven

For example timeouts and network errors. In these cases the generated Error instance doesn't contain a response object.

2017-04-11 01:46 UTC, micky2be requested changes

2017-04-11 01:46 UTC, micky2be commented on src/index.js
> +				error.response &&	error.response.status === 401 && this.authenticated()) {
white space problem

2017-04-11 01:46 UTC, micky2be commented on src/index.js
> +				if (!err.response || (err.response && err.response.data.status !== 401)) {
No need for the double check. The following should be enough
`(!err.response ||  err.response.data.status !== 401)`

2017-04-11 07:43 UTC, peteruithoven commented on src/index.js
> +				if (!err.response || (err.response && err.response.data.status !== 401)) {
Good point!

2017-04-11 10:50 UTC, merged

2017-04-11 11:21 UTC, peteruithoven commented
Thanks guys! 
I'm hoping these (#53, the safari private mode fix, #54, #55, #56) where all the fixes I wanted to get done for the time being, so could the last changes be included into a new release?

2017-04-12 07:19 UTC, micky2be commented
No problem, gonna make a new release asap

2017-04-20 08:04 UTC, peteruithoven commented
@micky2be friendly reminder for that release.

2017-04-20 09:06 UTC, micky2be commented
Done, thanks for the reminder

2017-04-20 10:13 UTC, peteruithoven commented
Thanks! :)